name: "FRP Client"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "2.0.1"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  frpcConfig: |
    [common]
    server_addr = "your_server_addr"
    server_port = 7000
    token = "your_token"

    [letsencryptvalidation]
    type = "http"
    local_port = "80"
    remote_port = "80"
    custom_domains = "your_domain.example.com"

    [homeassistant]
    type = "https"
    local_port = 8123
    remote_port = 443
    custom_domains = "your_domain.example.com"

schema:
  frpcConfig: str
